version: '3.9'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: fastapi
    ports:
      - "8000:80"
    depends_on:
      - qdrant
    volumes:
      - ./back_end:/app/back_end
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt

  qdrant:
    image: qdrant/qdrant:v1.0.0
    ports:
      - "6333:6333"
      - "6334:6334"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./front_end:/app/front_end
    command: sh -c "npm install && npm run dev"
