version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:80"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
    volumes:
      - .:/app
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:v1.0.0
    ports:
      - "6333:6333"
    environment:
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
