# Frontend stage
FROM node:18 AS frontend

# Set working directory for frontend build
WORKDIR /app/front_end

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all frontend files
COPY . ./

RUN npm run build

# Build the frontend
CMD ["npm", "run", "dev"]
